<a href="https://colab.research.google.com/github/Caffeine-Coders/Sentiment-Analysis-Project/blob/main/backend/testing_of_the_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 101.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 101.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 33.4 MB/s eta 0:00:00


In [ ]:
!pip install datasets

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.7/468.7 KB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.9/132.9 KB 19.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.2/212.2 KB 31.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 KB 17.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 63.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.6/264.6 KB 34.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.8/158.8 KB 26.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 17.5 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset, list_datasets

In [ ]:
dataset1 = load_dataset("tweet_eval", "sentiment")

Extracting data files:   0%|          | 0/6 [00:00<?, ?it/s]

Generating train split:   0%|          | 0/45615 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/12284 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2000 [00:00<?, ? examples/s]

Dataset tweet_eval downloaded and prepared to /root/.cache/huggingface/datasets/tweet_eval/sentiment/1.1.0/12aee5282b8784f3e95459466db4cdf45c6bf49719c25cdb0743d71ed0410343. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
dataset2 = load_dataset("mteb/tweet_sentiment_extraction")

Extracting data files:   0%|          | 0/2 [00:00<?, ?it/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Dataset json downloaded and prepared to /root/.cache/huggingface/datasets/mteb___json/mteb--tweet_sentiment_extraction-19a608df77d581ad/0.0.0/fe5dd6ea2639a6df622901539cb550cf8797e5a6b2dd7af1cf934bed8e233e6e. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
dataset3 = load_dataset("amazon_polarity")

Generating train split:   0%|          | 0/3600000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/400000 [00:00<?, ? examples/s]

Dataset amazon_polarity downloaded and prepared to /root/.cache/huggingface/datasets/amazon_polarity/amazon_polarity/3.0.0/a27b32b7e7b88eb274a8fa8ba0f654f1fe998a87c22547557317793b5d2772dc. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
dataset4 = load_dataset("sentiment140")

Generating train split:   0%|          | 0/1600000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/498 [00:00<?, ? examples/s]

Dataset sentiment140 downloaded and prepared to /root/.cache/huggingface/datasets/sentiment140/sentiment140/1.0.0/f81c014152931b776735658d8ae493b181927de002e706c4d5244ecb26376997. Subsequent calls will reuse this data.


  0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
dataset5 = load_dataset("imdb")

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

Dataset imdb downloaded and prepared to /root/.cache/huggingface/datasets/imdb/plain_text/1.0.0/d613c88cf8fa3bab83b4ded3713f1f74830d1100e171db75bbddb80b3345c9c0. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
dataset7 = load_dataset("rotten_tomatoes")

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Dataset rotten_tomatoes downloaded and prepared to /root/.cache/huggingface/datasets/rotten_tomatoes/default/1.0.0/40d411e45a6ce3484deed7cc15b82a53dad9a72aafd9f86f8f227134bec5ca46. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
dataset8 = load_dataset("sst2")

Generating train split:   0%|          | 0/67349 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/872 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1821 [00:00<?, ? examples/s]

Dataset sst2 downloaded and prepared to /root/.cache/huggingface/datasets/sst2/default/2.0.0/9896208a8d85db057ac50c72282bcb8fe755accc671a57dd8059d4e130961ed5. Subsequent calls will reuse this data.


  0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
import numpy as np
import tensorflow as tf
from transformers import RobertaTokenizerFast
tokenizer = RobertaTokenizerFast.from_pretrained("roberta-base")
from transformers import TFRobertaForSequenceClassification
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import load_model

from tensorflow.keras.callbacks import ModelCheckpoint
early_stop = EarlyStopping(monitor='val_sparse_categorical_accuracy', patience=3, verbose=3)

model = TFRobertaForSequenceClassification.from_pretrained("roberta-base", num_labels = 3)
model.compile(optimizer=Adam(3e-5), metrics = [tf.keras.metrics.SparseCategoricalAccuracy()])

All model checkpoint layers were used when initializing TFRobertaForSequenceClassification.

Some layers of TFRobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
No loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.


In [ ]:
tokenized_test1 = tokenizer(dataset1['test']["text"], return_tensors="np", padding=True)
tokenized_test1 = dict(tokenized_test1)
testlabels1 = np.array(dataset1['test']["label"]) 

In [ ]:
tokenized_test2 = tokenizer(dataset2['test']["text"], return_tensors="np", padding=True)
tokenized_test2 = dict(tokenized_test2)

testlabels2 = np.array(dataset2['test']["label"]) 

In [ ]:
tokenized_test3 = tokenizer(dataset3['test'][:1000]["content"], return_tensors="np", padding = True, truncation = True)
tokenized_test3 = dict(tokenized_test3)
testlabels3 = np.array(dataset3['test'][:1000]["label"]) 
testlabels3[testlabels3 == 1] = 2


In [ ]:
tokenized_test4 = tokenizer(dataset4['test']["text"], return_tensors="np", padding=True)
tokenized_test4 = dict(tokenized_test4)

testlabels4 = np.array(dataset4['test']["sentiment"]) 
testlabels4[testlabels4==2] = 0
testlabels4[testlabels4==4] = 2

In [ ]:
tokenized_test5 = tokenizer(dataset5['test']["text"], return_tensors="np", padding=True, truncation = True)
tokenized_test5 = dict(tokenized_test5)

testlabels5 = np.array(dataset5['test']["label"]) 
testlabels5[testlabels5 == 1] = 2


In [ ]:
tokenized_test7 = tokenizer(dataset7['test']["text"], return_tensors="np", padding=True)
tokenized_test7 = dict(tokenized_test7)
testlabels7 = np.array(dataset7['test']["label"]) 
testlabels7[testlabels7 == 1] = 2


In [ ]:

tokenized_test8 = tokenizer(dataset8['test']["sentence"], return_tensors="np", padding=True)
tokenized_test8 = dict(tokenized_test8)

testlabels8= np.array(dataset8['test']["label"]) 
testlabels8[testlabels8 == 1] = 2


In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights3.h5')
results = model.evaluate(dict(tokenized_test1), testlabels1)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test2), testlabels2)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test3), testlabels3)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test4), testlabels4)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test5), testlabels5)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test7), testlabels7)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test8), testlabels8)
print("test loss, test accuracy = ", results)


384/384 [==============================] - 19s 33ms/step - loss: 11.5539 - sparse_categorical_accuracy: 0.4229
test loss, test accuracy =  [11.553922653198242, 0.42290785908699036]
111/111 [==============================] - 7s 32ms/step - loss: 9.7358 - sparse_categorical_accuracy: 0.4805
test loss, test accuracy =  [9.73580551147461, 0.48047539591789246]
32/32 [==============================] - 2s 70ms/step - loss: 0.1280 - sparse_categorical_accuracy: 0.9540
test loss, test accuracy =  [0.12803921103477478, 0.9539999961853027]
16/16 [==============================] - 0s 29ms/step - loss: 0.8806 - sparse_categorical_accuracy: 0.6928
test loss, test accuracy =  [0.8805947303771973, 0.6927710771560669]
782/782 [==============================] - 116s 148ms/step - loss: 0.2019 - sparse_categorical_accuracy: 0.9344
test loss, test accuracy =  [0.20192913711071014, 0.9343600273132324]
34/34 [==============================] - 1s 30ms/step - loss: 0.4505 - sparse_categorical_accuracy: 0.8499


In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights6.h5')
results = model.evaluate(dict(tokenized_test1), testlabels1)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test2), testlabels2)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test3), testlabels3)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test4), testlabels4)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test5), testlabels5)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test7), testlabels7)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test8), testlabels8)
print("test loss, test accuracy = ", results)

384/384 [==============================] - 13s 33ms/step - loss: 10.0878 - sparse_categorical_accuracy: 0.4199
test loss, test accuracy =  [10.087810516357422, 0.41989579796791077]
111/111 [==============================] - 3s 31ms/step - loss: 8.5601 - sparse_categorical_accuracy: 0.4762
test loss, test accuracy =  [8.560060501098633, 0.4762308895587921]
32/32 [==============================] - 2s 70ms/step - loss: 0.1205 - sparse_categorical_accuracy: 0.9540
test loss, test accuracy =  [0.12049784511327744, 0.9539999961853027]
16/16 [==============================] - 0s 28ms/step - loss: 0.6873 - sparse_categorical_accuracy: 0.6687
test loss, test accuracy =  [0.6873286962509155, 0.6686747074127197]
782/782 [==============================] - 115s 148ms/step - loss: 0.1654 - sparse_categorical_accuracy: 0.9386
test loss, test accuracy =  [0.16535411775112152, 0.9385600090026855]
34/34 [==============================] - 1s 30ms/step - loss: 0.4000 - sparse_categorical_accuracy: 0.8462


In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights16.h5')
results = model.evaluate(dict(tokenized_test1), testlabels1)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test2), testlabels2)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test3), testlabels3)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test4), testlabels4)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test5), testlabels5)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test7), testlabels7)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test8), testlabels8)
print("test loss, test accuracy = ", results)

384/384 [==============================] - 62s 161ms/step - loss: 11.7463 - sparse_categorical_accuracy: 0.4298
test loss, test accuracy =  [11.746333122253418, 0.42982742190361023]
111/111 [==============================] - 17s 150ms/step - loss: 9.9083 - sparse_categorical_accuracy: 0.4850
test loss, test accuracy =  [9.90831470489502, 0.4850028157234192]
32/32 [==============================] - 16s 511ms/step - loss: 0.1131 - sparse_categorical_accuracy: 0.9580
test loss, test accuracy =  [0.11312985420227051, 0.9580000042915344]
16/16 [==============================] - 2s 125ms/step - loss: 0.7429 - sparse_categorical_accuracy: 0.6847
test loss, test accuracy =  [0.7429108619689941, 0.6847389340400696]
34/34 [==============================] - 5s 137ms/step - loss: 0.4254 - sparse_categorical_accuracy: 0.8452
test loss, test accuracy =  [0.425405353307724, 0.8452157378196716]
57/57 [==============================] - 8s 136ms/step - loss: nan - sparse_categorical_accuracy: 0.0000e+00

In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights18.h5')
results = model.evaluate(dict(tokenized_test1), testlabels1)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test2), testlabels2)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test3), testlabels3)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test4), testlabels4)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test5), testlabels5)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test7), testlabels7)
print("test loss, test accuracy = ", results)

results = model.evaluate(dict(tokenized_test8), testlabels8)
print("test loss, test accuracy = ", results)

384/384 [==============================] - 13s 33ms/step - loss: 10.5600 - sparse_categorical_accuracy: 0.4326
test loss, test accuracy =  [10.560025215148926, 0.43259525299072266]
111/111 [==============================] - 3s 31ms/step - loss: 8.7516 - sparse_categorical_accuracy: 0.5221
test loss, test accuracy =  [8.751614570617676, 0.5220713019371033]
32/32 [==============================] - 2s 71ms/step - loss: 0.1716 - sparse_categorical_accuracy: 0.9370
test loss, test accuracy =  [0.171578511595726, 0.9369999766349792]
16/16 [==============================] - 0s 28ms/step - loss: 0.8383 - sparse_categorical_accuracy: 0.7309
test loss, test accuracy =  [0.8383272886276245, 0.7309237122535706]
782/782 [==============================] - 115s 148ms/step - loss: 0.1958 - sparse_categorical_accuracy: 0.9334
test loss, test accuracy =  [0.19579830765724182, 0.9334400296211243]
34/34 [==============================] - 1s 30ms/step - loss: 0.3539 - sparse_categorical_accuracy: 0.9024
te

In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights20.h5')

In [ ]:
#---------------------------------------love
text = "i love you :))))))"
test_encodings = tokenizer(text, return_tensors='np')
output = model(**test_encodings)

print(output)
logits = output.logits
label = tf.argmax(logits, axis = 1).numpy()
print(label)

predicted_label = [2]

print(type(label))
metric = tf.keras.metrics.Accuracy()
metric.update_state(label, predicted_label)
metric.result().numpy()

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ -2.7035625, -21.340834 ,   2.4348505]], dtype=float32)>, hidden_states=None, attentions=None)
[2]
<class 'numpy.ndarray'>


1.0

In [ ]:
text = "without a proper wicket taking bowler dont dream of going to playoffs"
test_encodings = tokenizer(text, return_tensors='np')
output = model(**test_encodings)

print(output)
logits = output.logits
label = tf.argmax(logits, axis = 1).numpy()
print(label)

predicted_label = [0]

print(type(label))
metric = tf.keras.metrics.Accuracy()
metric.update_state(label, predicted_label)
metric.result().numpy()


TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 2.6425066, -8.878586 , -1.4105743]], dtype=float32)>, hidden_states=None, attentions=None)
[0]
<class 'numpy.ndarray'>


1.0

In [ ]:
text = "Legacy like Sachin,Fan following like No other,Captaincy like Ponting,Power like Gayle,Cool like Williamson,Keeper like Gilchrist,Longetivity like Anderson,Ability like Kohli &amp;An Aroma and Charisma like no other"
test_encodings = tokenizer(text, return_tensors='np')
output = model(**test_encodings)

print(output)
logits = output.logits
label = tf.argmax(logits, axis = 1).numpy()
print(label)

predicted_label = [2]

print(type(label))
metric = tf.keras.metrics.Accuracy()
metric.update_state(label, predicted_label)
metric.result().numpy()


TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 1.2012106, 10.86407  , -1.376536 ]], dtype=float32)>, hidden_states=None, attentions=None)
[1]
<class 'numpy.ndarray'>


0.0

In [ ]:
# ------------------hate------------------------------------------------
text = "🤩"
test_encodings = tokenizer(text, return_tensors='np')
output = model(**test_encodings)

print(output)
logits = output.logits
label = tf.argmax(logits, axis = 1).numpy()
print(label)

predicted_label = [0]

print(type(label))
metric = tf.keras.metrics.Accuracy()
metric.update_state(label, predicted_label)
metric.result().numpy()

TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 1.1172347,  9.656916 , -1.2507695]], dtype=float32)>, hidden_states=None, attentions=None)
[1]
<class 'numpy.ndarray'>


0.0

In [ ]:
import pandas as pd


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/DatasetsforSentimentAnalysis/output.csv', header = None)
print(data)

                                                     0  1
0    @Mahadev27696271 @pratiks64299422 @itsSSR @msd...  1
1                                      @ms_dhoni_077 👍  2
2    IPL 2023: @msdhoni can continue to play for th...  1
3    Chahar issues massive ‘MS Dhoni’ update after ...  1
4    @BCCI @mastercardindia Like it or not but @ImR...  1
..                                                 ... ..
129    @Mahadev27696271 @itsSSR @msdhoni शुभ रात्रि 🙏🙏  1
130                 @Kohled_Eyes_ Ratan tata  ms dhoni  1
131           @msdhoni ENJOY 😊 https://t.co/9QyFOrG0hv  2
132           This time IPL is all about ms dhoni smi😊  2
133                             MS Dhoni in 2011 final  1

[134 rows x 2 columns]


In [ ]:
text = data[0].values.tolist()
lab = data[1].values
print(type(text))

<class 'list'>


In [ ]:
tokenized_test1 = tokenizer(text, return_tensors="np", padding = True, truncation = True)
tokenized_test1 = dict(tokenized_test1)
testlabels1 = np.array(lab) 

In [ ]:
model.load_weights('/content/drive/MyDrive/model_custom/best_weights20.h5')
result = model.evaluate(tokenized_test1, testlabels1)
print("loss, accuracy", result)

In [ ]:
import re

def remove_mentions_and_links(text):
    # Remove @ mentions
    text = re.sub(r'@\w+', '', text)
    # Remove links
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'www\S+', '', text)
    return text

In [ ]:
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
t = remove_mentions_and_links(text[61])
model.load_weights('/content/drive/MyDrive/model_custom/best_weights18.h5')
test_encodings = tokenizer(t, return_tensors='np')
output = model(**test_encodings)

print(output)
logits = output.logits
label = tf.argmax(logits, axis = 1).numpy()
print(label)




TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[  1.8085105 , -18.516928  ,  -0.06284688]], dtype=float32)>, hidden_states=None, attentions=None)
[0]
